// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCDq4dwe8DSl0jHPScUNm9AjDNEsbeWJs',
    appId: '1:159956471841:web:fda93322433371cb089360',
    messagingSenderId: '159956471841',
    projectId: 'chatapp-b05ea',
    authDomain: 'chatapp-b05ea.firebaseapp.com',
    storageBucket: 'chatapp-b05ea.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXD42ocIHtuKBShQtDDiGpnGm0-twBA8w',
    appId: '1:159956471841:android:a716469a19550be2089360',
    messagingSenderId: '159956471841',
    projectId: 'chatapp-b05ea',
    storageBucket: 'chatapp-b05ea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQyMZ_TMT1VvzMz4ZFwDEeK9ehRjvLUlg',
    appId: '1:159956471841:ios:f2e686448c7578e5089360',
    messagingSenderId: '159956471841',
    projectId: 'chatapp-b05ea',
    storageBucket: 'chatapp-b05ea.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQyMZ_TMT1VvzMz4ZFwDEeK9ehRjvLUlg',
    appId: '1:159956471841:ios:a5ad9ce861e00e12089360',
    messagingSenderId: '159956471841',
    projectId: 'chatapp-b05ea',
    storageBucket: 'chatapp-b05ea.appspot.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
